---
grails:
    profile: rest-api
    codegen:
        defaultPackage: rest.api
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - swagger/json
              - text/json   
            hal:
              - swagger/hal+json
              - swagger/hal+xml
            xml:
              - text/xml
              - swagger/xml
            atom: swagger/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: swagger/rss+xml
            text: text/plain
            all: '*/*'            
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
---
# tag::dataSource[]
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    username: root
    password: ''
# end::dataSource[]

# tag::dbUrl[]
environments:
    development:
        dataSource:
            dbCreate: update # <1>
            url: jdbc:mysql://localhost:3306/swagger?useUnicode=yes&characterEncoding=UTF-8
    # end::dbUrl[]